baseURL = "https://rtoolbox.rbind.io/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Rtoolbox"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "RToolbox"
  author = "Sister Analyst"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[params.logo]
url = "logo.jpg"

[outputs]
#home = [ "HTML", "RSS", "JSON"]
home = ["HTML"]



[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i>GitHub"
identifier = "ds"
url = "https://github.com/SisterAnalyst"
weight = 10


